baseURL = "https://lundekvam.io"
languageCode = "en-us"
title = "lundekvam.io"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
#  [[menu.main]]
#    name = "Blog"
#    url = "/posts/"
#    weight = 1
#  [[menu.main]]
#    name = "About"
#    url = "/about/"
#    weight = 4

[params]
    since = 2011
    author = "Daniel Lundekvam"                           # Author's name
    avatar = "/images/me/avatar.jpeg"           # Author's avatar
    subtitle = "Techlead / Architect / Developer"         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "about" # post or other
    
[params.social]
    GitHub = "danislu"
    Linkedin = "daniellundekvam"
    Twitter = "danislu"
    Email   = "daniel@lundekvam.io"
    Instagram = "danislu2"
