baseURL = "https://danislu.github.io"
title = "daniel lundekvam"
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""
Paginate = 5

preserveTaxonomyNames = true

[params]
  description = "utvikler, pappa, løper etc"
  dateFormat = "2017, Sep 16"
  copyrightOwner = "daniel lundekvam"
  copyrightStartYear = "2017"
  favicon = "favicon.ico"
  hideEntryNavigation = false
  hideSocialMenu = false
  showReadTime = true
  customCSS = ["css/prism.css"]
  customJS = ["js/prism.js", "js/custom.js"]

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

[params.opengraph]
  [params.opengraph.facebook]
    admins = ""
    appid = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  facebook = ""

[author]
  name = "Daniel"

[author.social]
  codepen = ""
  email = "danislu@gmail.com"
  facebook = ""
  github = "danislu"
  instagram = "danislu2"
  twitter = "danislu"
  linkedin = "daniellundekvam"

[permalinks]
  page = "/:slug/"

[[menu.main]]
  name = "Blog"
  weight = -70
  identifier = "danislu"
  url = "https://danislu.github.io"

# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
